Read GB version 4 data, change MODIS input filename and stop using WF…
NOAA-GSL/GSL-prep-chem pull request #6
Opened 2023-02-14 19:09 UTC by lipan-NOAA

The PR for the issue #5

2023-02-14 19:22 UTC, lipan-NOAA commented
@WalterKolczynski-NOAA @SamuelTrahanNOAA

Can you review the code and approve it next week? The NCO requires this update by March.

@XianwuXue-NOAA Please suggest which version should we use for the new tag?

Thanks

2023-02-14 19:27 UTC, WalterKolczynski-NOAA requested changes
Please remove the old code instead of just commenting it out.

Also, please check the indentation of the new lines. Much of it does not match the surrounding code (look out for tabs vs spaces).

2023-02-14 19:31 UTC, XianwuXue-NOAA commented
@lipan-NOAA I think you can use **gefs_v12.3.5** as tag name

2023-02-15 00:43 UTC, lipan-NOAA commented
@WalterKolczynski-NOAA just updated, please check. Thanks.

2023-02-15 02:43 UTC, XianwuXue-NOAA commented on workflow/emc-global/scripts/exglobal_prep_chem.sh
> +gbbepx_pattern=${gbbepx_pattern:-'$GBBEPX_DATA_DIR/${local_name}-${CASE}${GTtile}_v4r0_blend_s${day}'}
Why does the GTtile was set value in the after the lines? Such as Line 138 and 206?

2023-02-15 03:56 UTC, lipan-NOAA commented
@XianwuXue-NOAA to reset GTtile, otherwise GTtile is always equal to "GT6" during copying

2023-02-15 04:51 UTC, XianwuXue-NOAA requested changes

2023-02-15 04:51 UTC, XianwuXue-NOAA commented on workflow/emc-global/scripts/exglobal_prep_chem.sh
> +gbbepx_pattern=${gbbepx_pattern:-'$GBBEPX_DATA_DIR/${local_name}-${CASE}${GTtile}_v4r0_blend_s${day}'}
Thanks I understood now.

2023-02-15 04:51 UTC, XianwuXue-NOAA commented on workflow/emc-global/scripts/exglobal_prep_chem.sh
> +	    export GTtile=GT$itile
Such added lines were using tab instead of spaces, you should use spaces to consistent with others.

2023-02-15 22:38 UTC, XianwuXue-NOAA approved these changes
Looks good to me.

2023-02-15 22:41 UTC, WalterKolczynski-NOAA approved these changes

2023-02-16 16:42 UTC, lipan-NOAA commented
@SamuelTrahanNOAA 
Can you approve it and create a tag "gefs_v12.3.5" ? Thanks

2023-02-17 20:55 UTC, merged

2023-02-27 20:35 UTC, XianwuXue-NOAA commented
@SamuelTrahanNOAA Could you create a new tag "gefs_v12.3.6" and delete the tag" gefs_v12.3.5? Because NCO/SPA created a new version of GEFS with minor change in global-workflow today, so I should do the corresponding changes. Sorry for the confusion and thank a lot for your time!

2023-02-27 20:48 UTC, SamuelTrahanNOAA commented
> new tag "gefs_v12.3.6" and delete the tag" gefs_v12.3.5

I just did it. Could you please look at the tag and confirm it is what you wanted?

2023-02-27 21:42 UTC, XianwuXue-NOAA commented
@SamuelTrahanNOAA Thank you very much for your quick changes. I just checked and confirmed it. Thanks again.